dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: vijayasankarn-github
    token:
      secure: yR9tH+TKgeJLDPZmfsZkKpL3HYhbuKcE73Ipims5nX8AqZ1eVHmgVBbBkld1Thc9Hdd+QiSmZ8bwkPnjv9u+LdXwMsJRmM3dcVKxqMZYUQjCzTYSRUhJ2cZ2gOlJ1x5UaSDLV1H8+M9voKLcGw7BbafCf5CNv2VLZ5CTodavlyho1V7SVMlexLASnxRWm38SzznjBWL0SsW1Qb+IhqPAuTHJYUfYdw2TS/+z54+DYg85bIJF/TAQsf7avBL3U2kBL7oIykFGuOFVphF1EXN/cGRtbrrTL+p91QgQBgRszbzqAJ3YmmbmZIHe89B+BgG4kB5/r7BVXDFYHyeZslplGSJAyzmPAI91eeLJyF3ekSDqFpV0r1zYohmr0C7Ly7zeWgswAoiSiFIuGy8MxR7PfWuBhJEdtrqdusNNnBJH833TgAY0SaRqjN9zWgW8jWE3+RZg4XzqDwvjGxMbNkrdGvUzlhDoJBPexkQxK3/UokEqb0JXLi8ib5AVGEI7/nhOZP967NcrRPYUn1ooP45HmPg116aCZ3PSjcxsLcW6iHdzyXGf3NA9GXOTmq3C42yhQEoEQBdMUwFdupWXQLhKlYV9hJBtcPIC2IFFFchpNSFIQdC8/5ZV/OvxBlmUeCJb+VG272UAf6S6fCf9dSFHsRkK4ITiX0mFeBYaSrFvL7c=
jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
  - "$HOME/.sonar/cache"
branches:
  only:
  - master
